apiVersion: v1
kind: Service
metadata:
  name: summarizer
  labels:
    app: summarizer
spec:
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  selector:
    app: summarizer
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarizer
  labels:
    app: summarizer
spec:
  selector:
    matchLabels:
      app: summarizer
  replicas: 2
  template:
    metadata:
      labels:
        app: summarizer
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5001"
        prometheus.io/path: "/metrics"
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: summarizer
          image: gcr.io/visma-interview/summary-service
          args: []
          ports:
            - containerPort: 50051
          resources:
            requests:
              memory: 256Mi
              cpu: 500m
            limits:
              memory: 768Mi
              cpu: 2500m
          readinessProbe:
            exec:
              command:
                [
                  "/bin/grpc_health_probe",
                  "-addr=:50051",
                  "-connect-timeout=100ms",
                  "-rpc-timeout=150ms",
                ]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command:
                [
                  "/bin/grpc_health_probe",
                  "-addr=:50051",
                  "-connect-timeout=100ms",
                  "-rpc-timeout=150ms",
                ]
            initialDelaySeconds: 10
